# Generated by Django 2.1.4 on 2019-03-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
    ]
