# Generated by Django 2.1.4 on 2019-03-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_tag_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='background_image/%Y/%m/%d/', verbose_name='文章图片')),
            ],
            options={
                'verbose_name': '文章头部默认背景图片',
                'verbose_name_plural': '文章头部默认背景图片',
            },
        ),
    ]
