# Generated by Django 2.1.4 on 2019-03-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name': '文章背景图片', 'verbose_name_plural': '文章背景图片'},
        ),
        migrations.AddField(
            model_name='img',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='img',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_image/%Y/%m/%d/'),
        ),
    ]
