# Generated by Django 2.1.4 on 2019-03-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190322_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='article_img/%Y/%m/%d/', verbose_name='文章图片'),
        ),
    ]
