# Generated by Django 2.1.4 on 2019-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20190503_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#666666', max_length=100, verbose_name='分类颜色'),
        ),
    ]
